### ISSUE TITLE
Port to an open source alternative to Matlab

### ISSUE THREAD

**Issue by anchapin** [mlab-upenn/mlep_v1.1#1]
I request that this project be ported to an open source alternative to Matlab such as GNU Octave. This would bring the cost down to use this product since Matlab licenses are expensive for commercial use.

**Comment by nxtruong** [comment]
This will involve porting the socket communication (as a server, not a client) to Octave (or Scilab, or whatever open source tools we want to port to). In Matlab, I use Java. But I believe it's not possible in Octave; perhaps we must use C. I would love to port MLE+ to open source tools, but don't have time right now. Moreover, I think Octave/Scilab is not very popular. If I plan to port MLE+, I probably choose Python, or a more modern scientific computation language like Julia.
